config/routes.rb
Rails.application.routes.draw do
  root :to => 'users#index'
  get 'home' => 'layouts#index'
  
  get 'connections/ranges/:start_date/:end_date/:unique_visitors/:max/:min(/:start_hour/:end_hour)' => 'connections#ranges'
  get 'connections/connections_between_dates/:start_date/:end_date/:group_by/:unique_visitors(/:start_hour/:end_hour)' => 'connections#connections_between_dates'
  get 'connections/total_seconds/:start_date/:end_date(/:start_hour/:end_hour)' => 'connections#total_seconds'
  get 'connections/avg_seconds/:start_date/:end_date(/:start_hour/:end_hour)' => 'connections#avg_seconds'
  get 'connections/total_seconds_grouped/:start_date/:end_date/:group_by(/:start_hour/:end_hour)' => 'connections#total_seconds_grouped'
  get 'connections/programs/:start_date/:end_date/:unique_visitors(/:start_hour/:end_hour)' => 'connections#programs'

  post 'login' => 'users#create'
  get 'logout' => 'users#destroy'
  get 'login_form' => 'users#login_form'
  resources :users

  get 'locations/countries/:start_date/:end_date/:unique_visitors(/:start_hour/:end_hour)' => 'locations#countries'
  get 'locations/countries_time/:start_date/:end_date(/:start_hour/:end_hour)' => 'locations#countries_time'
  get 'locations/regions/:start_date/:end_date/:country/:unique_visitors(/:start_hour/:end_hour)' => 'locations#regions'
  get 'locations/regions_time/:start_date/:end_date/:country(/:start_hour/:end_hour)' => 'locations#regions_time'
  get 'locations/cities/:start_date/:end_date/:country/:region/:unique_visitors(/:start_hour/:end_hour)' => 'locations#cities'
  get 'locations/cities_time/:start_date/:end_date/:country/:region(/:start_hour/:end_hour)' => 'locations#cities_time'
  get 'locations/get_countries' => 'locations#get_countries'
  get 'locations/get_regions/:country' => 'locations#get_regions'

  get 'ranking/country_ranking/:start_date/:end_date(/:start_index/:count)(/:start_hour/:end_hour)' => 'ranking#country_ranking'
  get 'ranking/region_ranking/:start_date/:end_date(/:start_index/:count)(/:start_hour/:end_hour)' => 'ranking#region_ranking'
  get 'ranking/city_ranking/:start_date/:end_date(/:start_index/:count)(/:start_hour/:end_hour)' => 'ranking#city_ranking'
  get 'ranking/user_agent_ranking/:start_date/:end_date(/:start_index/:count)(/:start_hour/:end_hour)' => 'ranking#user_agent_ranking'
  get 'ranking/top_links_ranking/:start_date/:end_date(/:start_hour/:end_hour)' => 'ranking#top_links_ranking'

  get 'sources' => 'sources#get_sources'
  post 'sources/:source' => 'sources#set_source', :constraints => {:source => /([a-zA-Z0-9].*)+\.[a-zA-Z0-9]+|Todos/}
  resources :sources

  get 'poll/:route' => "polling#poll", :constraints => {:route => /.*/}

  get 'real_time/last_connections' => 'real_time#last_connections'

end

app/models/user.rb
=begin
IceCast-Stats is system for statistics generation and analysis
for an IceCast streaming server
Copyright (C) 2015  René Balay Lorenzo <rene.bl89@gmail.com>

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
=end

class User
  include Mongoid::Document
  include ActiveModel::SecurePassword
  
  field :login, type: String
  field :password_digest, type: String
  
  has_secure_password
  
end

app/controllers/users_controller.rb
=begin
IceCast-Stats is system for statistics generation and analysis
for an IceCast streaming server
Copyright (C) 2015  René Balay Lorenzo <rene.bl89@gmail.com>

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
=end

class UsersController < ApplicationController
  protect_from_forgery with: :exception
  skip_before_filter :check_authentication, :only => [:index, :create, :login_form]
  before_action :session_params, only: [:create]
   
  def index
    unless authenticated?
      render :layout => false
    else
      redirect_to home_path
    end
  end
  
  def create
    user = User.where(login: params[:session][:login].downcase).first
    # Si el usuario es nil, no queremos probar a autenticarlo, puesto que sería un intento de acceso a una clase nula
    if !user
      abort :wrong_login, "El usuario introducido no ha sido dado de alta en el sistema"
    elsif !user.authenticate(params[:session][:password])
      abort :wrong_password, "La contraseña no es válida"
    else
      log_in(user)
      redirect_to home_path
    end
  end
  
  def destroy
    log_out
    redirect_to root_path
  end
  
  def login_form
    render :layout => false
  end
  
  private
  # Método genérico de generación de mensaje flash con redirección a página de inicio
  def abort cause, message
    flash[cause] = message
    redirect_to login_form_path
  end
  
  def session_params
    params.require(:session).permit(:login, :password)
  end
  
end

app/views/users/_login_form.html.erb
<!--
IceCast-Stats is system for statistics generation and analysis
for an IceCast streaming server
Copyright (C) 2015  René Balay Lorenzo <rene.bl89@gmail.com>

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
-->

  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="modalLoginLabel">Login</h4>
      </div>
      <% flash.each do |name, msg| -%>
      	<div class="alert alert-danger alert-dismissible fade in" role="alert">
  			<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  			<%= msg %>
		</div>
      <% end -%>
      <%= form_for(:session, url: login_path) do |f| %>
      	<div class="modal-body">
        	<%= f.label :login %>
        	<%= f.text_field :login, class: 'form-control' %>
        	<%= f.label :password %>
        	<%= f.password_field :password, class: 'form-control' %>
      	</div>
      	<div class="modal-footer">
        	<%= f.submit "Login", class: "btn btn-primary" %>
      	</div>
      <% end %>
    </div>
  </div>

app/views/users/index.html.erb
<!--
IceCast-Stats is system for statistics generation and analysis
for an IceCast streaming server
Copyright (C) 2015  René Balay Lorenzo <rene.bl89@gmail.com>

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
-->

<!DOCTYPE html>
<html>
<head>
  <title>IceCastStats</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'root_page' %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller.controller_name %>">

<div id="jumboWelcomePage" class="jumbotron">
<h1 class="text-center">IceCast-Stats</h1>

<p class="text-center">
	Bienvenid@ a IceCast-Stats, una aplicación web para el análisis y generación de estadísticas para un servidor de
	streaming IceCast.
</p>

<p id="adminQuestion" class="text-center">¿Eres administrador?. Por favor, identifícate.</p>

<div id="buttonLogin">
	<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#modalLogin">Login</button>
</div>
</div>

<div class="modal fade" id="modalLogin" tabindex="-1" role="dialog" aria-labelledby="modalLoginLabel" aria-hidden="true">
	<%= render(partial: "login_form") %>
</div>
</body>
</html>

app/views/users/login_form.html.erb
<!--
IceCast-Stats is system for statistics generation and analysis
for an IceCast streaming server
Copyright (C) 2015  René Balay Lorenzo <rene.bl89@gmail.com>

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
-->

<!DOCTYPE html>
<html>
<head>
  <title>IceCastStats</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'root_page' %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="panel panel-default">
  <div class="panel-body">
  	<h1>Inicia sesión en IceCast-Stats</h1>
  </div>
</div>
<%= render(partial: "login_form") %>

</html>